name: Deploy Oblako

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: unnecessary
        if_key_exists: replace
        config: |
          Host *
            StrictHostKeyChecking no
        
    - name: Fix permissions
      run: |
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with direct SSH
      run: |
        ssh -v -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} '
          cd /var/www/oblako && \
          sudo -u www-data git fetch origin && \
          sudo -u www-data git reset --hard origin/main && \
          sudo systemctl restart oblako.service
        '
