name: Deploy Oblako

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: |
        ssh ubuntu@${{ secrets.SERVER_HOST }} '
          cd /var/www/oblako && \
          sudo -u www-data git fetch origin && \
          sudo -u www-data git reset --hard origin/main && \
          sudo systemctl restart oblako.service
        '
